### ISSUE TITLE
Unable to Lauch

### ISSUE THREAD

**Issue by DeltaPanda** [FTBTeam/FTB-Ultimate-Reloaded#360]
* **Modpack Version**: FTB Ultimate Reloaded 1.12.2

* **Issue**: If i have downloaded the pack and click on the button start, just nothing happens.
The button is for 1 sec. in another grey and then its like i have never pressed it.

* **Link to Log or Crash File Paste**: FTB Launcher logs:
Logging in...
Beginning authlib authentication attempt
successfully created YggdrasilAuthenticationService
Login complete.
Checking local assets file, for MC version 1.12.2 Please wait! 
Using backupLink for versions/1.12.2/1.12.2.json
Setting up native libraries for FTB Ultimate Reloaded v Recommended Version MC 1.12.2
Syncing Assets:
Java Path: C:\Program Files\Java\jre1.8.0_241\bin\javaw.exe
Pack: FTB Ultimate Reloaded 1.12.2
Setting MinMemory to 256
Setting MaxMemory to 10240
[19:06:10] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[19:06:10] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraftforge.fml.common.launcher.FMLTweaker
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_241]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_241]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: the entire modpack

**Comment by 016Nojr** [comment]
Please try again, and post new logs since there's a new launcher
